name: SpeechActivityDetection
   params:
      duration: 2.0
      batch_size: 64
      per_epoch: 1
      parallel: 6

data_augmentation:
   name: AddNoise
   params:
      snr_min: 10
      snr_max: 20
      collection: MUSAN.Collection.BackgroundNoise

feature_extraction:
   name: RawAudio
   params:
      sample_rate: 16000

architecture:
   name: pyannote.audio.models.PyanNet
   params:
      rnn:
         unit: LSTM
         hidden_size: 128
         num_layers: 2
         bidirectional: True
      ff:
         hidden_size: [128, 128]

scheduler:
   name: CyclicScheduler
   params:
      learning_rate: auto
      epochs_per_cycle: 14